### PR TITLE
[WIP] Implement floordiv operator

### LINKED ISSUE #180: `//(floordiv)` is not implemented yet
```sh
[DEBUG] compiler\erg_compiler\compile.rs:0157: the compiling process has started.
[DEBUG] compiler\erg_parser\parse.rs:0223: the parsing process has started.
[DEBUG] compiler\erg_parser\parse.rs:0224: token stream: [NatLit 1, FloorDiv //, NatLit 2, EOF ]
[DEBUG] compiler\erg_parser\parse.rs:0250: 
  (1) entered try_reduce_module, cur: NatLit 1
[DEBUG] compiler\erg_parser\parse.rs:0954: 
   (2) entered try_reduce_chunk, cur: NatLit 1
[DEBUG] compiler\erg_parser\parse.rs:1360: 
    (3) entered try_reduce_bin_lhs, cur: NatLit 1
[DEBUG] compiler\erg_parser\parse.rs:1774: 
     (4) entered try_reduce_lit, cur: NatLit 1
[DEBUG] compiler\erg_parser\parse.rs:1360: 
    (3) entered try_reduce_bin_lhs, cur: NatLit 2
[DEBUG] compiler\erg_parser\parse.rs:1774: 
     (4) entered try_reduce_lit, cur: NatLit 2
[DEBUG] compiler\erg_parser\parse.rs:0237: the parsing process has completed (errs: 0).
[DEBUG] compiler\erg_parser\parse.rs:0238: AST:
`//`:
    1
    2
[DEBUG] compiler\erg_parser\desugar.rs:0051: the desugaring process has started.
[DEBUG] compiler\erg_parser\desugar.rs:0055: AST (desugared):
`//`:
    1
    2
[DEBUG] compiler\erg_parser\desugar.rs:0056: the desugaring process has completed.
[DEBUG] compiler\erg_parser\desugar.rs:0051: the desugaring process has started.
[DEBUG] compiler\erg_parser\desugar.rs:0055: AST (desugared):
`//`:
    1
    2
[DEBUG] compiler\erg_parser\desugar.rs:0056: the desugaring process has completed.
[DEBUG] compiler\erg_compiler\lower.rs:1188: the AST lowering process has started.
[DEBUG] compiler\erg_compiler\lower.rs:1189: the type-checking process has started.
[DEBUG] compiler\erg_compiler\reorder.rs:0032: the reordering process has started.
[DEBUG] compiler\erg_compiler\reorder.rs:0090: the reordering process has completed:
`//`:
    1
    2
[DEBUG] compiler\erg_compiler\lower.rs:1033: entered lower_expr
[DEBUG] compiler\erg_compiler\lower.rs:0401: entered lower_bin(`//`:
    1
    2)
[DEBUG] compiler\erg_compiler\lower.rs:1033: entered lower_expr
[DEBUG] compiler\erg_compiler\lower.rs:1033: entered lower_expr
thread '<unnamed>' panicked at 'not yet implemented', compiler\erg_compiler\error.rs:51:14
```

### PR DESCRIPTION
**Pull request by GreasySlug**
Fixes #180.

Allow the `//(floordiv)` operator to be used for each type

Changes proposed in this PR:
- Add `//` operator
- Add register_builtin_impl()
- Add try_floordiv()

I couldn't implement it and would appreciate any advice.

I debugged it and noticed that the `lhs` was weird, but couldn't figure out how to fix it.

```sh
[DEBUG] compiler\erg_compiler\lower.rs:1270: entered lower_expr
[DEBUG] compiler\erg_compiler\lower.rs:1270: entered lower_expr
[DEBUG] compiler\erg_compiler\context\inquire.rs:1109: Found:
callee: ::__floordiv__(: |R: Type; 'L <: FloorDiv('R)|(lhs: 'L, rhs: 'R) -> 'L.Output)
found: |R: Type; 'L <: FloorDiv('R)|(lhs: 'L, rhs: 'R) -> 'L.Output
[DEBUG] compiler\erg_compiler\context\inquire.rs:1114: Instantiated:
instance: (lhs: ?L(<: FloorDiv(?R(: Type(:> Never, <: Obj))[1])(cyclicity: Not))[1], rhs: ?R(: Type(:> Never, <: Obj))[1]) -> ?L(<: FloorDiv(?R(: Type(:> Never, <: Obj))[1])(cyclicity: Not))[1].Output
pos_args: (1 (: {Nat(1), }), 2 (: {Nat(2), }))
kw_args: ()
[DEBUG] compiler\erg_compiler\context\tyvar.rs:1286: trying sub_unify:
maybe_sub: {Nat(1), }
maybe_sup: ?L(<: FloorDiv(?R(: Type(:> Never, <: Obj))[1])(cyclicity: Not))[1]
[DEBUG] compiler\erg_compiler\context\compare.rs:0131: answer: FloorDiv(?R(: Type(:> Never, <: Obj))[1]) :> Nat == false
[DEBUG] compiler\erg_compiler\context\compare.rs:0131: answer: FloorDiv(?R(: Type(:> Never, <: Obj))[1]) :> Nat == false
[DEBUG] compiler\erg_compiler\context\compare.rs:0131: answer: FloorDiv(?R(: Type(:> Never, <: Obj))[1]) :> {Nat(1), } == false
[DEBUG] compiler\erg_compiler\context\inquire.rs:0940: semi-unification failed with ::__floordiv__(: |R: Type; 'L <: FloorDiv('R)|(lhs: 'L, rhs: 'R) -> 'L.Output)
{Nat(1), } !<: ?L(<: FloorDiv(?R(: Type(:> Never, <: Obj))[1])(cyclicity: Not))[1]
[DEBUG] compiler\erg_compiler\lower.rs:1539: HIR (not resolved, current errs: 1):

[DEBUG] compiler\erg_compiler\lower.rs:1542: HIR (resolved):

[DEBUG] compiler\erg_compiler\lower.rs:1561: the AST lowering process has failed. errs: 1
Error[#0949]: File <stdin>, line 1, in <module>
1│ 1//2
   ^^^^
TypeError: the type of `//`::lhs is mismatched:
expected:  ?L(<: FloorDiv(?R(: Type(:> Never, <: Obj))[1])(cyclicity: Not))[1]
but found: {Nat(1), }
```

@mtshiba

### CODE REVIEW

**Comment by mtshiba** [comment]
Type checks are now passed. Code generation has not been implemented yet, but I'll leave it to you since it is so easy. Just add `BINARY_FLOOR_DIVIDE`.

File: compiler/erg_type/value.rs [hunk 1]
```diff
@@ -686,6 +686,30 @@ impl ValueObj {
...
+        match (self, other) {
+            (Self::Int(l), Self::Int(r)) => Some(Self::Int(l / r)),
+            (Self::Nat(l), Self::Nat(r)) => Some(Self::Nat(l / r)),
+            (Self::Float(l), Self::Float(r)) => Some(Self::Float((l / r).floor())),
+            (Self::Int(l), Self::Nat(r)) => Some(Self::Int(l / r as i32)),
+            (Self::Nat(l), Self::Int(r)) => Some(Self::Int(l as i32 / r)),
+            (Self::Float(l), Self::Nat(r)) => Some(Self::Float((l / r as f64).floor())),
+            (Self::Nat(l), Self::Float(r)) => Some(Self::Float((l as f64 / r).floor())),
+            (Self::Float(l), Self::Int(r)) => Some(Self::Float((l / r as f64).floor())),
+            (Self::Int(l), Self::Float(r)) => Some(Self::Float((l as f64 / r).floor())),
```
Comment (GreasySlug) [inline compiler/erg_type/value.rs:699]: I've modified the type cast and floor() to match python.
Is this correct?

**Comment by mtshiba** [comment]
Thanks!
