### PR TITLE
Fixed an issue where multiple chunks can be declared on a single line

### LINKED ISSUE #281: Multiple declarations on a single line
### Describe the bug?

Normally, it should be separated by a semicolon, but it can be written on a single line with a blank space.

### Reproducible code

```
a = 1 b = 2 c = 3
print! a, b, c
```

### Expected result

Invalid Syntax

### Actual result

```
1 2 3
```

### Additional context

_No response_

### Erg version

Erg 0.6.0-beta.1

### Python version

python3.10.8

### OS

Windows 10

### PR DESCRIPTION
**Pull request by GreasySlug**
Fixes #281

It is possible to declare multiple chunks on a single line with whitespace

It is an invalid syntax and should be detected as an error in the parser

 - [x] declaration
 - [x] Array
 - [x] Set
 - [x] Dict
 - [x] Record
 - [x] Tuple
 - [ ] ~~Class~~ 
@mtshiba

### CODE REVIEW

File: compiler/erg_parser/error.rs [hunk 1]
```diff
@@ -155,6 +155,68 @@ impl LexError {
             loc,
         ))
     }
+
+    pub fn invalid_chunk_error(errno: usize, loc: Location) -> LexError {
+        let msg = switch_lang!(
+            "japanese" => "チャンクの後に無効なチャンクが付随しています",
+            "simplified_chinese" => "",
+            "traditional_chinese" => "",
+            "english" => "Chunk is followed by invalid chunk",
```
Comment (GreasySlug) [inline compiler/erg_parser/error.rs:164]: I wrote `chunk`, but is there a more appropriate name?

**Comment by GreasySlug** [comment]
Spaces are basically removed when the token is converted to a token.
This change requires a high degree of knowledge of Parser and Erg language syntax, as the sequence of tokens changes the meaning.
I do not have that, so any further changes would be difficult to deal with.

The issue I'm concerned about is the difficulty in processing EOF
There is this issue that has not yet been addressed by the block, etc.
A new line basically solves the problem, but EOFs after tokens are usually a source of error.

I think it is possible to add Dedent and EOF processing to everything, but it is not a very good implementation.

File: compiler/erg_parser/error.rs (hunk 1 above)
Comment (mtshiba) [reply compiler/erg_parser/error.rs:164]: The formal name for the smallest unit of execution, usually "each line," is chunk, which is correct. This is a loan word from Lua.
However, since it is an unfamiliar term, it seems that it would be OK to simply indicate as an invalid syntax and display a hint says that a line break or semicolon should be added.

**Comment by GreasySlug** [comment]
If there was no separator, parsing was continued skipping the error point.
This resulted in multiple syntax errors that were detected as errors in modules, etc.
Therefore, analysis is now stopped when an error occurs.

**Comment by GreasySlug** [comment]
Detects as an error if there is no delimiter or line break after chunk and there is a token
After detection, since the token behind the detection is often not only expr, it is ignored until `TC::Separator`.

**Comment by GreasySlug** [comment]
Tuple has different error message, and Class has different error location

```
1 | 1 2 3
  : -
  : `- should add `;` or newline

SyntaxError: invalid syntax

7 | Class {name = Str age = Nat}
  :        --------------
  :                     `- should add `;` or newline
```

 - Tuple
The first element of Tuple is not processed by a unique function.
 - Class 
Consecutive identifiers are handled as arguments on the parser side

I think these issue would be better to create another PR instead of this one.

File: compiler/erg_parser/parse.rs [hunk 2]
```diff
@@ -30,10 +30,11 @@ use TokenKind::*;
 macro_rules! debug_call_info {
     ($self: ident) => {
         $self.level += 1;
+        let space= " ".repeat($self.level);
         log!(
             c GREEN,
             "\n{} ({}) entered {}, cur: {}",
-            " ".repeat($self.level),
+            space.replace("    ", "･"),
```
Comment (mtshiba) [inline compiler/erg_parser/parse.rs:37]: I think `"･".repeat(($self.level as f32 / 4.0).floor() as usize)` is more elegant and efficient.

File: compiler/erg_parser/parse.rs [hunk 3]
```diff
@@ -935,7 +992,16 @@ impl Parser {
         ));
         loop {
             match self.peek() {
-                Some(arg) if arg.is(Symbol) || arg.category_is(TC::Literal) => {
+                Some(arg)
```
Comment (mtshiba) [inline compiler/erg_parser/parse.rs:995]: I think this change isn't needed (since the tests all pass). Could you explain why did you make this change?

Comment (GreasySlug) [reply compiler/erg_parser/parse.rs:995]: The following cases are for errors

```
{"a" 1 "b": 2}
```
```
1 "b": 2 # this code is valid in parser
a x: Nat # similar to this
```

As you can see in the discord, this is an ad-hoc implementation to prevent parser-side handling
as function arguments

Comment (mtshiba) [reply compiler/erg_parser/parse.rs:994]: This implementation seems to be wrong.

スクリーンショット 2022-12-18 115114

Comment (mtshiba) [reply compiler/erg_parser/parse.rs:994]: This implementation seem to be wrong.

スクリーンショット 2022-12-18 115605

Comment (GreasySlug) [reply compiler/erg_parser/parse.rs:994]: This issue same as following code
```
 (1) entered try_reduce_module, cur: NatLit 1
[DEBUG] compiler\erg_parser\parse.rs:0986: 
 (2) entered try_reduce_chunk, cur: NatLit 1
[DEBUG] compiler\erg_parser\parse.rs:1504: 
 (3) entered try_reduce_bin_lhs, cur: NatLit 1
[DEBUG] compiler\erg_parser\parse.rs:2297: 
･ (4) entered try_reduce_lit, cur: NatLit 1
[DEBUG] compiler\erg_parser\parse.rs:0176: error caused by: try_reduce_moduleError[#0178]: File <stdin>, line 1, 
Error[#0178]: File <stdin>, line 1, 

1 | 1 2
  : -
  : `- should add `;` or newline

SyntaxError: invalid syntax
```

Tuple does not process the first element with a unique function unless it is followed by a comma.

That's why, the error return to the module and cannot be fixed to a tuple-specific error.

To fix this, we need a different approach when parsing Tuple.

Comment (mtshiba) [reply compiler/erg_parser/parse.rs:994]: `i = 2 j = 1` and `{ "a": 1 "b": 1 }` are different kinds of problems in Erg parsing.
I recognize that this issue addresses the former, and I think you have done a fine job in this regard.
The problem I point out in this review is caused by trying to solve the latter.
To solve the latter requires a different idea (well, I have some in mind), and a different issue should be made.
So, there is no need to return this PR to draft.

**Comment by GreasySlug** [comment]
> i = 2 j = 1 and { "a": 1 "b": 1 } are different kinds of problems in Erg parsing.

The comma error in the collection is a different issue than this PR and has been removed from this.
So, I squashed commits.
